from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors

from addons.combined_actions import CombinedActions

"""
This pytest test was automatically generated by TestProject
    Project: Test Projects
    Package: TestProject.Generated.Tests.TestProjects
    Test: Login
    Generated by: Eduardo Andres Urzuas (eduardoandresu.u@gmail.com)
    Generated on 09/02/2021, 03:56:35
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'CreateAccount' test."""
    # Test Parameters
    TestEmail = "testemail@test.com"
    Password = ""  # This was a SECRET parameter and therefore its value is empty

    # 1. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//a[3]/span[1]")
    span.click()

    # 2. Click 'Log In'
    log_in = driver.find_element(By.XPATH,
                                 "//a[. = 'Log In']")
    log_in.click()

    # 3. Click 'login[username]'
    login_username_ = driver.find_element(By.CSS_SELECTOR,
                                          "#email")
    login_username_.click()

    # 4. Run Clear 'Email Address' contents and type '{TestEmail}'
    email_address = (By.XPATH, "//*[@id=\"email\"]")
    driver.addons().execute(
        CombinedActions.clearandtypeaction(
            keys=f'{TestEmail}'), *email_address)

    # 5. Run Clear 'Password input' contents and type '{Password}'
    password_input = (By.XPATH, "//*[@id=\"pass\"]")
    driver.addons().execute(
        CombinedActions.clearandtypeaction(
            keys=f'Password123'), *password_input)

    # 6. Click 'send'
    send = driver.find_element(By.CSS_SELECTOR,
                               "#send2")
    send.click()
