from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors


"""
This pytest test was automatically generated by TestProject
    Project: Test Projects
    Package: TestProject.Generated.Tests.TestProjects
    Test: Verify details page
    Generated by: Eduardo Andres Urzuas (eduardoandresu.u@gmail.com)
    Generated on 09/02/2021, 03:56:35
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'CreateAccount' test."""
    # Test Parameters
    BookName = "A TALE OF TWO CITIES"


    # 2. Click 'View Details'
    view_details = driver.find_element(By.XPATH,
                                       "//li[1]//a[. = 'View Details']")
    view_details.click()

    # 3. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 4. Get text from 'A TALE OF TWO CITIES BOOK'
    a_tale_of_two_cities_book = driver.find_element(By.XPATH,
                                                    "//span[contains(text(), 'A Tale of Two Cities')]")
    step_output = a_tale_of_two_cities_book.get_attribute("value")
    #assert "f'{BookName}'" in step_output.text

    assert a_tale_of_two_cities_book.text == BookName
