from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors

from addons.visible_elements_operations import VisibleElementsOperations

"""
This pytest test was automatically generated by TestProject
    Project: Test Projects
    Package: TestProject.Generated.Tests.TestProjects
    Test: Verify Contact information
    Generated by: Eduardo Andres Urzuas (eduardoandresu.u@gmail.com)
    Generated on 09/02/2021, 03:56:35
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'CreateAccount' test."""
    # Test Parameters
    TestEmail = "testemail@test.com"

    # 1. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 2. Click 'P'
    p = driver.find_element(By.XPATH,
                            "//div[3]/div[2]/div[1]//p")
    p.click()

    # 3. 'Contact Info' contains text '{TestEmail}'?
    contact_info = (
        By.XPATH, "//*[@id=\"top\"]/body/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div[2]/div[1]/div/div[2]/p/text()[2]")
    driver.addons().execute(
        VisibleElementsOperations.containstextifvisibleweb(
            text=f'{TestEmail}',
            timeout=""), *contact_info)
