from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors


"""
This pytest test was automatically generated by TestProject
    Project: Test Projects
    Package: TestProject.Generated.Tests.TestProjects
    Test: Logout
    Generated by: Eduardo Andres Urzuas (eduardoandresu.u@gmail.com)
    Generated on 09/02/2021, 03:56:35
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'CreateAccount' test."""

    # 1. Click 'Account1'
    account1 = driver.find_element(By.XPATH,
                                   "//a[. = '\n                \n                Account\n            ']")
    account1.click()

    # 2. Click 'Log Out'
    log_out = driver.find_element(By.XPATH,
                                  "//a[. = 'Log Out']")
    log_out.click()
