from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.decorator import report_assertion_errors


"""
This pytest test was automatically generated by TestProject
    Project: Test Projects
    Package: TestProject.Generated.Tests.TestProjects
    Test: Search Item
    Generated by: Eduardo Andres Urzuas (eduardoandresu.u@gmail.com)
    Generated on 09/02/2021, 03:56:35
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'CreateAccount' test."""
    # Test Parameters
    SearchItem = "Books"

    # 1. Click 'q'
    q = driver.find_element(By.CSS_SELECTOR,
                            "#search")
    q.click()

    # 2. Type '{SearchItem}' in 'q'
    q = driver.find_element(By.CSS_SELECTOR,
                            "#search")
    q.send_keys(f'{SearchItem}')

    # 3. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()
